jenkins:
  systemMessage: "Simple seed job example"
jobs:
  - script: |
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/wqhhust/javatest.git')
              }
          }
      }
