- name: Playbook to Install Packages
  hosts: localhost
  connection: local
  tasks:
    - name: disable csrf so we can install plugin
      ansible.builtin.lineinfile:
        path: /etc/default/jenkins
        regexp: 'JAVA_ARGS="- Djava.awt.headless=true'
        line: JAVA_ARGS="- Djava.awt.headless=true – Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"

    - name: restart jenkins
      service:
        name: jenkins
        state: restarted

    - pause:
        minutes: 1

    - name: Install Jenkins plugins
      jenkins_plugin:
        name: "{{ item }}"
        url_username: "test"
        url_password: "test"
      with_items:
        - artifactory
        - build-pipeline-plugin
        - kubernetes
        - mailer
        - sonar
        - maven-plugin
        - ec2
        - build-pipeline-plugin
        - blueocean
        - git
        - workflow-aggregator
        - perfpublisher
        - github
